<?php

/**
 * @file
 * Contains infinite_flipboard_node_view.module.
 */

use Drupal\Core\Url;
use Drupal\views\ViewExecutable;

/**
 * Prepares variables for RSS feed templates.
 *
 * Default template: views-view-rss.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A ViewExecutable object.
 *   - rows: The raw row data.
 */
function infinite_flipboard_preprocess_views_view_flipboard_rss(array &$variables) {
  $view = $variables['view'];
  if ($view->id() == 'infinite_taxonomy_term' && $view->getDisplay()->display['display_options']['style']['type'] == 'flipboard_rss') {
    // For some reason, the link comes out with an encoded asterisk at the
    // end, we replace it and use the aliased path.
    $actual_link = Url::fromRoute('<current>')->setAbsolute()->toString();
    $variables['link'] = $actual_link;
  }
}
