<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 * Alter the list of allowed widget plugins per view mode and entity type.
 *
 * Use this hook to restrict or allow the usage
 * of given plugins in the widgets form.
 *
 * @param array &$plugin_definitions
 *   The array of plugin definitions.
 *   Keys are plugin ids, values are plugin labels.
 * @param string &$default_plugin
 *   The default plugin id to use on the widgets form.
 * @param array $context
 *   Consists of following keys:
 *   - 'view_mode': The machine name of the given view mode.
 *   - 'belonging_entity_type': The given entity type id.
 */
function infinite_imagepin_allowed_widget_plugins_alter(array &$plugin_definitions, &$default_plugin, array $context) {
    // Don't include the default text widget.
    unset($plugin_definitions['text']);
    $default_plugin = 'product';
}

/**
 * Implements hook_js_alter().
 */
function infinite_imagepin_js_alter(&$javascript, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {

  // Swap out jQuery to use an updated version of the library.

    $imagePinViewJsPath = drupal_get_path('module', 'imagepin') . '/js/imagepin.view.js';
    if (isset($javascript[$imagePinViewJsPath])) {
         $javascript[$imagePinViewJsPath]['data'] = drupal_get_path('module', 'infinite_imagepin') . '/js/infinite_imagepin.view.js';
    }

    // Remove js slick files
    unset($javascript[drupal_get_path('module', 'imagepin') . '/js/extensions/imagepin.slick.js']);
}


function infinite_imagepin_css_alter(&$css, \Drupal\Core\Asset\AttachedAssetsInterface $assets) {

    // Remove defaults.css file.
    unset($css[drupal_get_path('module', 'imagepin') . '/css/extensions/imagepin.slick.css']);
}

function infinite_imagepin_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  if(isset($element['imagepin'])){
    $element['imagepin']['#prefix'] = '<div class="imagepin-modal-link">';
    $element['imagepin']['#attached']['library'][] = 'infinite_imagepin/admin';
  }
  return;
}
