<?php

/**
 * Implements hook_page_attachments().
 */
function infinite_wishlist_page_attachments(array &$attachments)
{
  if (false === \Drupal::service('router.admin_context')->isAdminRoute(
    \Drupal::routeMatch()->getRouteObject()
  )) {
    $attachments['#attached']['library'][] = 'infinite_wishlist/basic';
  }
}

/**
 * Implements hook_theme().
 */
function infinite_wishlist_theme() {
  return [
    'infinite_wishlist_item' => [
      'variables' => [
        'product' => [],
        'product_name_without_brand' => '',
        'image' => null,
        'provider' => '',
      ],
    ],
    'infinite_wishlist_page' => [
      'variables' => [],
    ],
    'infinite_wishlist_flyout' => [
      'variables' => [],
    ],
  ];
}
