<?php

use Drupal\views\ViewExecutable;

/**
 * Implementatyion of hook_views_post_render().
 */
function infinite_lexicon_views_post_render(ViewExecutable $view, &$output, $cache) {

  /** @var \Drupal\views\Plugin\views\display\DisplayPluginBase $display */
  $display = $view->getDisplay();

  if($view->id() == 'lexicon_overview' && $display->display['id'] == 'page_1') {
    $groups = &$output['#rows'];
    foreach ($groups as $i => &$group) {
      $first_key = key($group['#rows']);
      $first_row = &$group['#rows'][$first_key];
      $entity = $first_row['#row']->_entity;
      $first_label = $entity->label();

      // Prepare group title with anchor ID.
      $groupTitle = '<span id="' . strtolower($group['#title']) . '">' . $group['#title'] . ' wie ' . $first_label . '</span>';
      $group['#title'] = [
        '#type' => 'markup',
        '#markup' => $groupTitle,
      ];
    }
  }

}