<?php

/**
 * @file
 * Module for adding custom Infinite blocks and block functions.
 */

use Drupal\Component\Utility\Html;
use Drupal\block\Entity\Block;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\user\Entity\User;


function infinite_blocks_theme() {
  return [
    'header_media' => array(
      'variables' => array('header_media' => NULL, 'header_title' => NULL),
    ),
    'outbrain' => array(
      'variables' => array('outbrain' => NULL),
    ),
    'logo_header' => array(
      'variables' => array('logo' => NULL, 'front_page' => NULL)
    ),
    'logo' => array(
      'variables' => array('logo' => NULL, 'front_page' => NULL)
    ),
    'modal_search' => array(
      'variables' => array()
    ),
    'modal_newsletter' => array(
      'variables' => array(
        'logo' => NULL,
        'groupId' => NULL,
        'headline' => NULL,
        'text' => NULL,
        'confirmation_headline' => NULL,
        'confirmation_text' => NULL,
      )
    ),
    'newsletter' => array(
      'variables' => array(
        'logo' => NULL,
        'groupId' => NULL,
        'headline' => NULL,
        'text' => NULL,
        'confirmation_headline' => NULL,
        'confirmation_text' => NULL,
      )
    ),
    'newsletter_large' => array(
      'variables' => array(
        'logo' => NULL,
        'groupId' => NULL,
        'headline' => NULL,
        'text' => NULL,
        'confirmation_headline' => NULL,
        'confirmation_text' => NULL,
      )
    ),
    'newsletter_men_large' => array(
      'variables' => array(
        'logo' => NULL,
        'groupId' => NULL,
        'headline' => NULL,
        'text' => NULL,
        'confirmation_headline' => NULL,
        'confirmation_text' => NULL,
      )
    ),
    'socials_bar' => array(
      'variables' => array(
        'use_parent_container' => NULL,
        'follow' => NULL,
        'include_wishlist_icon' => null,
        'include_tipser_icon' => null,
      )
    ),
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function infinite_blocks_form_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  /* @var \Drupal\block\BlockInterface $block */
  $block = $form_state->getFormObject()->getEntity();
  $default_class = 'block-' . Html::getClass($block->getPluginId());
  $default_id = 'block-' . Html::getId($block->getPluginId());

  // This will automatically be saved in the third party settings.
  $form['third_party_settings']['#tree'] = TRUE;

  $form['third_party_settings']['infinite_blocks']['id'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS id'),
    '#description' => t('Customize the styling of this block by adding id. (Default CSS id: %default_id)', array('%default_id' => $default_id)),
    '#default_value' => !empty ($block->getThirdPartySetting('infinite_blocks', 'id')) ? $block->getThirdPartySetting('infinite_blocks', 'id') : [],
  );

  $form['third_party_settings']['infinite_blocks']['classes'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS class(es)'),
    '#description' => t('Customize the styling of this block by adding CSS classes. Separate multiple classes by spaces. (Default CSS class: %default_class)', array('%default_class' => $default_class)),
    '#default_value' => !empty ($block->getThirdPartySetting('infinite_blocks', 'classes')) ? $block->getThirdPartySetting('infinite_blocks', 'classes') : [],
  );
  $form['third_party_settings']['infinite_blocks']['title_tag'] = array(
    '#type' => 'select',
    '#title' => t('Title Tag'),
    '#description' => t('Customize the output of this title tag.'),
    '#default_value' => !empty ($block->getThirdPartySetting('infinite_blocks', 'title_tag')) ? $block->getThirdPartySetting('infinite_blocks', 'title_tag') : 'div',
    '#options' => array(
      'nav' => 'nav',
      'div' => 'div',
      'span' => 'span',
      'h1' => 'h1',
      'h2' => 'h2',
      'h3' => 'h3',
      'h4' => 'h4',
      'h5' => 'h5',
      'h6' => 'h6',
    ),
  );
  $form['third_party_settings']['infinite_blocks']['block_tag'] = array(
    '#type' => 'select',
    '#title' => t('Block Tag'),
    '#description' => t('Customize the type of this block tag.'),
    '#default_value' => !empty ($block->getThirdPartySetting('infinite_blocks', 'block_tag')) ? $block->getThirdPartySetting('infinite_blocks', 'block_tag') : 'div',
    '#options' => array(
      'nav' => 'nav',
      'div' => 'div',
      'span' => 'span',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function infinite_blocks_preprocess_block(&$variables) {
  // Blocks coming from page manager widget does not have id.
  if (!empty($variables['elements']['#id'])) {
    $block = Block::load($variables['elements']['#id']);
    $id = !empty ($block->getThirdPartySetting('infinite_blocks', 'id')) ? $block->getThirdPartySetting('infinite_blocks', 'id') : [];
    $classes = !empty ($block->getThirdPartySetting('infinite_blocks', 'classes')) ? explode(' ', $block->getThirdPartySetting('infinite_blocks', 'classes')) : [];
    $title_tag = !empty ($block->getThirdPartySetting('infinite_blocks', 'title_tag')) ? $block->getThirdPartySetting('infinite_blocks', 'title_tag') : 'div';
    $block_tag = !empty ($block->getThirdPartySetting('infinite_blocks', 'block_tag')) ? $block->getThirdPartySetting('infinite_blocks', 'block_tag') : 'div';

    $variables['attributes']['id'] = $id;
    $variables['attributes']['class'] = $classes;
    $variables['title_tag'] = $title_tag;
    $variables['block_tag'] = $block_tag;
    $variables['use_container'] = !(empty($id) && empty($classes));

    $variables['content']['#use_parent_container'] = $variables['use_container'];

    if ('infinite_blocks_socials' === $variables['base_plugin_id']) {
      if (\Drupal::moduleHandler()->moduleExists('infinite_wishlist')) {
        if ('header_large' === $block->getRegion()) {
          $variables['content']['#include_wishlist_icon'] = true;
        }
      }
    }

    if (in_array($variables['base_plugin_id'], ['system_menu_block', 'infinite_blocks_socials'])) {
      $tipserIsActivated = (bool)\Drupal::config('tipser_client.config')->get('tipser_activated');
      $variables['content']['#include_tipser_icon'] = $tipserIsActivated;
      $variables['include_tipser_icon'] = $tipserIsActivated;
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function infinite_blocks_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'default' || $variables['view_mode'] == 'full') {

    /* @var Drupal\node\Entity\Node $node */
    $node = $variables['elements']['#node'];

    // Used for H1 and H2 tag handling on term pages with header block.
    if (($node->hasField('field_header_media') && !$node->field_header_media->isEmpty()) ||
      ($node->hasField('field_header_title') && !$node->field_header_title->isEmpty())) {

      $variables['has_header_block'] = TRUE;
    }
  }
}

/**
 * Implements hook_preprocess_taxonomy_term().
 */
function infinite_blocks_preprocess_taxonomy_term(&$variables) {
  if (in_array($variables['view_mode'], ['default', 'full', 'amp'])) {

    /* @var Drupal\taxonomy\Entity\Term $term */
    $term = $variables['elements']['#taxonomy_term'];

    // Used for H1 and H2 tag handling on term pages with header block.
    if (($term->hasField('field_header_media') && !$term->field_header_media->isEmpty()) ||
      ($term->hasField('field_header_title') && !$term->field_header_title->isEmpty())) {
      $variables['has_header_block'] = TRUE;
      if ($term->hasField('field_hide_title') && ($term->field_hide_title->value !== '0')) {
        $variables['term_title_hidden'] = TRUE;
      }
    }
  }
}

/**
 * Implements hook_preprocess_user().
 */
function infinite_blocks_preprocess_user(&$variables) {
  if ($variables['elements']['#view_mode'] == 'default' || $variables['elements']['#view_mode'] == 'full') {

    /* @var Drupal\user\Entity\User $user */
    $user = $variables['elements']['#user'];

    // Used for H1 and H2 tag handling on term pages with header block.
    if (($user->hasField('field_header_media') && !$user->field_header_media->isEmpty()) ||
      ($user->hasField('field_header_title') && !$user->field_header_title->isEmpty())) {

      $variables['has_header_block'] = TRUE;
    }
  }
}

/**
 * Helper function to get blocks from dynamic region.
 */
function _infinite_blocks_get_dyn_region_blocks($allowed_regions) {
  // Retrieve active theme.
  $theme = \Drupal::theme()->getActiveTheme()->getName();

  // Retrieve theme regions.
  $available_regions = system_region_list($theme, 'REGIONS_ALL');

  // Validate allowed regions with available regions.
  $regions = array_intersect(array_keys($available_regions), $allowed_regions);

  foreach ($regions as $key => $region) {
    // Load region blocks.
    $blocks = \Drupal::entityTypeManager()
      ->getStorage('block')
      ->loadByProperties(array('theme' => $theme, 'region' => $region));
    uasort($blocks, 'Drupal\block\Entity\Block::sort');

    // Capture viewable blocks for dynBlocks.
    foreach ($blocks as $key => $block) {
      if ($block->access('view')) {
        $dynBlocks[] = $block;
      }
    }
  }

  // Return dynamic blocks or FALSE.
  if (!empty($dynBlocks)) {
    return $dynBlocks;
  }
  return FALSE;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function infinite_blocks_theme_suggestions_header_media_alter(array &$suggestions, array $variables) {
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $suggestions[] = header_media__front;
  }
}
