<?php
/**
 * @file
 * Module that allows editors to select a view mode for paragraphs.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function infinite_paragraphs_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['field_paragraph'])) {
    return;
  }

  foreach (Element::children($form['field_paragraph']['widget']) as $index) {
    if (isset($form['field_paragraph']['widget'][$index]['subform']['field_p_view_mode'])) {
      _infinite_paragraphs_view_mode_widget_alter($form['field_paragraph']['widget'][$index]['subform']['field_p_view_mode']['widget'], $index);
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function infinite_paragraphs_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['field_paragraphs'])) {
    return;
  }

  foreach (Element::children($form['field_paragraphs']['widget']) as $index) {
    if (isset($form['field_paragraphs']['widget'][$index]['subform']['field_p_view_mode'])) {
      _infinite_paragraphs_view_mode_widget_alter($form['field_paragraphs']['widget'][$index]['subform']['field_p_view_mode']['widget'], $index);
    }
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function infinite_paragraphs_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  if ($view_mode == 'flexible' && $entity->getEntityTypeId() == 'paragraph' && $entity->hasField('field_p_view_mode')) {
    $view_mode = $entity->field_p_view_mode->value ?: 'small';
  }
  if ($entity->getEntityTypeId() == 'user' && $view_mode == 'default') {
    $ref = $entity->_referringItem;
    // fetch view mode from parent item
    if ($ref && ($parent = $ref->getEntity()) && $parent->hasField('field_user_view_mode')) {
      $view_mode = $parent->field_user_view_mode->value;
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function infinite_paragraphs_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (isset($build['field_paragraphs'])) {

    // Add dynamic blocks in 'Full' view mode.
    if ($build['#view_mode'] == 'full') {
      _infinite_paragraphs_add_dyn_blocks($build);
    }

    _infinite_paragraphs_decorate_group($build['field_paragraphs'], _infinite_paragraphs_layout_group($build['field_paragraphs'], array('small' ,'middle')), 'group_outer', $build);
  }
}

/**
 * Implemens hook_ENTITY_TYPE_view_alter().
 */
function infinite_paragraphs_taxonomy_term_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (isset($build['field_paragraph'])) {
    _infinite_paragraphs_decorate_group($build['field_paragraph'], _infinite_paragraphs_layout_group($build['field_paragraph'], array('small' ,'middle')), 'group_outer', $build);
  }
  else if (isset($build['field_paragraphs'])) {
    _infinite_paragraphs_decorate_group($build['field_paragraphs'], _infinite_paragraphs_layout_group($build['field_paragraphs'], array('small' ,'middle')), 'group_outer', $build);
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function infinite_paragraphs_user_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (isset($build['field_paragraphs'])) {
    _infinite_paragraphs_decorate_group($build['field_paragraphs'], _infinite_paragraphs_layout_group($build['field_paragraphs'], array('small' ,'middle')), 'group_outer', $build);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function infinite_paragraphs_theme_suggestions_container_alter(array &$suggestions, array $variables) {
  if (!empty($variables['element']['#type'])) {
    $suggestions[] = 'container__' . $variables['element']['#type'];

    if (isset($variables['element']['#parent']) && isset($variables['element']['#parent']['#node'])) {
      /** @var \Drupal\node\Entity\Node $node */
      $node = $variables['element']['#parent']['#node'];
      $suggestions[] = 'container__' . $node->getType();
      $suggestions[] = 'container__' . $node->getType() . '__' . $variables['element']['#type'];
    }
    else if (isset($variables['element']['#parent']) && isset($variables['element']['#parent']['#taxonomy_term'])) {
      $term = $variables['element']['#parent']['#taxonomy_term'];
      $suggestions[] = 'container__term__' . $term->bundle();
      $suggestions[] = 'container__term__' . $term->bundle() . '__' . $variables['element']['#type'];
    }
    else if (isset($variables['element']['#parent']) && isset($variables['element']['#parent']['#user'])) {
      $term = $variables['element']['#parent']['#user'];
      $suggestions[] = 'container__' . $term->bundle();
      $suggestions[] = 'container__' . $term->bundle() . '__' . $variables['element']['#type'];
    }
  }
}

function infinite_paragraphs_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  $paragraph = $variables['elements']['#paragraph'];
  if($paragraph->hasField('field_user_view_mode')) {
    $viewmode = $paragraph->field_user_view_mode->value;
    $suggestions[] = 'paragraph__'  . $paragraph->bundle() . '__' . $viewmode;
  }
}

/**
 * Implements hook_preprocess_container().
 */
function infinite_paragraphs_preprocess_container(&$variables) {
  if (isset($variables['element']['#parent'])) {
    $variables['parent'] = $variables['element']['#parent'];

    if (isset($variables['element']['#parent']['#node'])) {
      $node = $variables['element']['#parent']['#node'];
      _infinite_paragraphs_get_parent_base_data($node, $variables);
    }
    elseif (isset($variables['element']['#parent']['#taxonomy_term'])) {
      $term = $variables['element']['#parent']['#taxonomy_term'];
      _infinite_paragraphs_get_parent_base_data($term, $variables);
    }
    elseif (isset($variables['element']['#parent']['#user'])) {
      $user = $variables['element']['#parent']['#user'];
      _infinite_paragraphs_get_parent_base_data($user, $variables);
    }
  }
}

/**
 * Returns first group of paragraphs suitable for the content group.
 *
 * @param array $paragraphs
 *
 * @param array $view_modes
 *
 * @return array
 */
function _infinite_paragraphs_layout_group(&$paragraphs, $view_modes) {
  $group = [];
  foreach (Element::children($paragraphs, TRUE) as $index) {
    if (in_array($paragraphs[$index]['#view_mode'], $view_modes)) {
      $group[] = $index;
    }
    elseif (!empty($group) && !in_array($paragraphs[$index]['#view_mode'], $view_modes)) {
      break;
    }
  }
  unset($paragraphs['#sorted']);
  return $group;
}

/**
 * Wraps the given group of paragraphs in a group container.
 *
 * @param array $paragraphs
 *   A list of paragraphs.
 *
 * @param array $group
 *   The indices of a group of paragraphs.
 *
 * @param $type
 *   An identifier used for the template suggestion.
 */
function _infinite_paragraphs_decorate_group(&$paragraphs, $group, $type, $build = array()) {
  if (!empty($group)) {
    $children = [];

    foreach ($group as $index) {
      $children[] = $paragraphs[$index];
      unset($paragraphs[$index]);
    }

    $paragraphs[$group[0]] = array(
      '#theme' => 'container',
      '#type' => $type,
      '#weight' => $children[0]['#weight'],
      '#children' => $children,
      '#parent' => $build,
    );

    ksort($paragraphs);

    foreach (Element::children($paragraphs) as $key => $value) {
      $paragraphs[$key] = $paragraphs[$value];
      if ($value > $key) {
        unset($paragraphs[$value]);
      }
    }

    if ($type == 'group_outer') {
      $small_group = _infinite_paragraphs_layout_group($children, array('small'));
      _infinite_paragraphs_decorate_group($paragraphs[$group[0]]['#children'], $small_group, 'group_inner', $build);
    }
  }
}

/**
 * Returns available view modes for user entities.
 *
 * @param FieldStorageDefinitionInterface $definition
 * @param FieldableEntityInterface $entity
 *
 * @return array
 */
function _infinite_paragraphs_available_user_view_modes(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
  /** @var \Drupal\Core\Entity\EntityDisplayRepositoryInterface $entityDisplayRepository */
  $entityDisplayRepository = \Drupal::service('entity_display.repository');
  // TODO maybe intersect these with allowed view modes
  $userViewModes = array_intersect_key($entityDisplayRepository->getViewModeOptions('user'), ['author_large' => '', 'author_small' => '', 'author_small_teaser' => '']);
  return $userViewModes;
}

/**
 * Returns allowed values for the paragraph view mode field.
 *
 * @param FieldStorageDefinitionInterface $definition
 * @param FieldableEntityInterface $entity
 *
 * @return array
 */
function _infinite_paragraphs_allowed_view_modes(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
  $cacheable = FALSE;

  if (in_array($entity->bundle(), array('content_teaser', 'gallery', 'instagram', 'pinterest', 'recent_content', 'term_teaser', 'twitter'))) {
    $allowed_view_modes = [
      'small' => 'Schmal',
    ];
  }
  else {
    $allowed_view_modes = [
      'full' => 'Volle Breite',
      'middle' => 'Mittel',
      'small' => 'Schmal',
    ];
  }

  return $allowed_view_modes;
}

/**
 * Modifies widget for paragraph view mode.
 *
 * - Disables widget if there is only one choice.
 *
 * @param array $form_element
 */
function _infinite_paragraphs_view_mode_widget_alter(array &$element, $index) {
  if (empty($element['#default_value'])) {
    if (array_key_exists('small', $element['#options'])) {
      $element['#default_value'] = array('small');
    }
  }

  if (count(array_diff(array_keys($element['#options']), array('_none'))) == 1) {
    $element['#disabled'] = TRUE;
  }
}

function _infinite_paragraphs_get_parent_base_data($entity, &$variables) {
  if ($entity->getEntityTypeId() == 'node') {
    $node = $entity;
    $alias_path = \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $node->id());
    if ($alias_path != '/') {
      $absolute_url = Url::fromUri('base:/' . $alias_path, array('absolute' => TRUE));
    }
    else {
      $absolute_url = Url::fromRoute('<front>', array('absolute' => TRUE));  // Extra handling for <front>.
    }
    $variables['parent']['url'] = $absolute_url->toString();
    $variables['parent']['label'] = $variables['parent']['title'];
    unset($variables['parent']['title']);
  }
  elseif ($entity->getEntityTypeId() == 'taxonomy_term') {
    $term = $entity;
    $alias_path = \Drupal::service('path.alias_manager')->getAliasByPath('/taxonomy/term/' . $term->id());
    if ($alias_path != '/') {
      $absolute_url = Url::fromUri('base:/' . $alias_path, array('absolute' => TRUE));
    }
    else {
      $absolute_url = Url::fromRoute('<front>', array('absolute' => TRUE));  // Extra handling for <front>.
    }
    $variables['parent']['url'] = $absolute_url->toString();
    $variables['parent']['label'] = $term->name->value;
  }
  elseif ($entity->getEntityTypeId() == 'user') {
    $user = $entity;
    $alias_path = \Drupal::service('path.alias_manager')->getAliasByPath('/user/' . $user->id());
    if ($alias_path != '/') {
      $absolute_url = Url::fromUri('base:/' . $alias_path, array('absolute' => TRUE));
    }
    $variables['parent']['url'] = $absolute_url->toString();
    $variables['parent']['label'] = $user->name->value;
  }

  // Get share image URL from teaser media.
  if ($entity->hasField('field_teaser_media') && !$entity->field_teaser_media->isEmpty()) {

    if (!empty($entity->field_teaser_media->entity) &&  // todo: check wyh some media entity reference seems to be empty here after isEmpty() check? example: node 6001
      $entity->field_teaser_media->entity->hasField('field_image') &&
      !$entity->field_teaser_media->entity->field_image->isEmpty()
    ) {

      $share_img_path = $entity->field_teaser_media->entity->field_image->entity->getFileUri();
      $share_img = ImageStyle::load(theme_get_setting('share_image_style'));
      if (is_object($share_img)) {
        $url = $share_img->buildUrl($share_img_path);
        $variables['share_img_url'] = $url;
      }
    }
  }

  $variables['parent']['facebook_share_button'] = theme_get_setting('facebook_share_button');
  $variables['parent']['whatsapp_share_button'] = theme_get_setting('whatsapp_share_button');
  $variables['parent']['pinterest_share_button'] = theme_get_setting('pinterest_share_button');
  $variables['parent']['twitter_share_button'] = theme_get_setting('twitter_share_button');
  $variables['parent']['twitter_share_via'] = theme_get_setting('twitter_share_via');
  $variables['parent']['email_share_button'] = theme_get_setting('email_share_button');
  $variables['parent']['whatsapp_share_text'] = theme_get_setting('whatsapp_share_text');
  $variables['parent']['email_share_text'] = theme_get_setting('email_share_text');
  $variables['parent']['email_subject'] = theme_get_setting('email_subject');
}

/**
 * Post render callback for adding dynamic blocks.
 */
function infinite_paragraphs_text_paragraph_post_render($children, $elements) {
  $dom = new DOMDocument();
  $dom->loadHTML(mb_convert_encoding($children, 'HTML-ENTITIES', 'UTF-8'));
  $pTags = $dom->getElementsByTagName('p');

  if ($pTags->length > 1 && $dynBlocks = _infinite_blocks_get_dyn_region_blocks(['dyn_blocks_node'])) {

    // Get render array of dynamic block.
    $block_content = \Drupal::entityTypeManager()
      ->getViewBuilder('block')
      ->view($dynBlocks[0]);  //TODO: prepare to render more then block number 1 in an article.

    // Add well formed XML placeholder element.
    $fragment = $dom->createDocumentFragment();
    $fragment->appendXML("<dynblock></dynblock>");
    $pTags->item(0)->appendChild($fragment);
    $children = $dom->saveHTML();

    // Replace XML placeholder element with rendered block.
    $dynBlockContent = \Drupal::service('renderer')->render($block_content);
    $children = str_replace('<dynblock></dynblock>', $dynBlockContent, $children);
  }

  return $children;
}

/**
 * Helper function to add x post render callbacks to given paragraphs.
 *
 * @param $build
 * @param string $paragraphType
 * @param array $paragraphViewModes
 */
function _infinite_paragraphs_add_dyn_blocks(&$build, $paragraphType = 'text', $paragraphViewModes = ['small']) {
  if ($dynBlocks = _infinite_blocks_get_dyn_region_blocks(['dyn_blocks_node'])) {
    $count = 0;
    foreach (Element::children($build['field_paragraphs'], TRUE) as $index) {
      if ($build['field_paragraphs'][$index]['#paragraph']->bundle() == $paragraphType &&
        in_array($build['field_paragraphs'][$index]['#view_mode'], $paragraphViewModes)) {

        $paragraphText = Html::load($build['field_paragraphs'][$index]['#paragraph']->field_text->value);
        $pTags = $paragraphText->getElementsByTagName('p');
        if ($pTags->length > 1 && function_exists('infinite_paragraphs_' . $paragraphType . '_paragraph_post_render')) {
          $build['field_paragraphs'][$index]['#post_render'][] = 'infinite_paragraphs_' . $paragraphType . '_paragraph_post_render';
          $count++;
        }

        if (count($dynBlocks) == $count) {
          break;
        }
      }
    }
  }
}