<?php
/**
 * @file
 * Module that allows editors to select a view mode for paragraphs.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;
use Drupal\infinite_media\MediaHelper;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function infinite_paragraphs_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['field_paragraphs'])) {
    return;
  }

  foreach (Element::children($form['field_paragraphs']['widget']) as $index) {
    if (isset($form['field_paragraphs']['widget'][$index]['subform']['field_p_view_mode'])) {
      _infinite_paragraphs_view_mode_widget_alter($form['field_paragraphs']['widget'][$index]['subform']['field_p_view_mode']['widget'], $index);
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function infinite_paragraphs_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!isset($form['field_paragraphs'])) {
    return;
  }

  foreach (Element::children($form['field_paragraphs']['widget']) as $index) {
    if (isset($form['field_paragraphs']['widget'][$index]['subform']['field_p_view_mode'])) {
      _infinite_paragraphs_view_mode_widget_alter($form['field_paragraphs']['widget'][$index]['subform']['field_p_view_mode']['widget'], $index);
    }
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function infinite_paragraphs_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  if ($view_mode == 'flexible' && $entity->getEntityTypeId() == 'paragraph' && $entity->hasField('field_p_view_mode')) {
    $view_mode = $entity->field_p_view_mode->value ?: 'small';
  }
  if ($entity->getEntityTypeId() == 'user' && $view_mode == 'default') {
    $ref = $entity->_referringItem;
    // fetch view mode from parent item
    if ($ref && ($parent = $ref->getEntity()) && $parent->hasField('field_user_view_mode')) {
      $view_mode = $parent->field_user_view_mode->value;
    }
  }
  if (\Drupal::service('router.amp_context')->isAmpRoute() && $entity->getEntityTypeId() == 'paragraph' && $entity->hasField('field_e_view_mode') && strpos($entity->field_e_view_mode->value, 'content_reference_') === 0) {
    $view_mode = 'amp_content_reference';
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function infinite_paragraphs_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (isset($build['field_paragraphs'])) {
    _infinite_paragraphs_decorate_group($build['field_paragraphs'], _infinite_paragraphs_layout_group($build['field_paragraphs'], array('small' ,'middle')), 'group_outer', $build);
  }
}

/**
 * Implemens hook_ENTITY_TYPE_view_alter().
 */
function infinite_paragraphs_taxonomy_term_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (isset($build['field_paragraphs'])) {
    _infinite_paragraphs_decorate_group($build['field_paragraphs'], _infinite_paragraphs_layout_group($build['field_paragraphs'], array('small' ,'middle')), 'group_outer', $build);
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function infinite_paragraphs_user_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (isset($build['field_paragraphs'])) {
    _infinite_paragraphs_decorate_group($build['field_paragraphs'], _infinite_paragraphs_layout_group($build['field_paragraphs'], array('small' ,'middle')), 'group_outer', $build);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function infinite_paragraphs_theme_suggestions_container_alter(array &$suggestions, array $variables) {
  if (!empty($variables['element']['#type'])) {
    $suggestions[] = 'container__' . $variables['element']['#type'];

    if (isset($variables['element']['#parent'])) {
      if (isset($variables['element']['#parent']['#node'])) {
        /** @var \Drupal\node\Entity\Node $node */
        $node = $variables['element']['#parent']['#node'];
        $suggestions[] = 'container__' . $node->getType();
        $suggestions[] = 'container__' . $node->getType() . '__' . $variables['element']['#type'];
      } else if (isset($variables['element']['#parent']['#taxonomy_term'])) {
        $term = $variables['element']['#parent']['#taxonomy_term'];
        $suggestions[] = 'container__term__' . $term->bundle();
        $suggestions[] = 'container__term__' . $term->bundle() . '__' . $variables['element']['#type'];
      } else if (isset($variables['element']['#parent']['#user'])) {
        $suggestions[] = 'container__user';
        $suggestions[] = 'container__user__' . $variables['element']['#type'];
      }
    }

  }
}

function infinite_paragraphs_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  $paragraph = $variables['elements']['#paragraph'];
  if($paragraph->hasField('field_user_view_mode')) {
    $viewmode = $paragraph->field_user_view_mode->value;
    $suggestions[] = 'paragraph__'  . $paragraph->bundle() . '__' . $viewmode;
  }
}

/**
 * Implements hook_preprocess_container().
 */
function infinite_paragraphs_preprocess_container(&$variables) {
  if (isset($variables['element']['#parent'])) {
    $variables['parent'] = $variables['element']['#parent'];

    if (isset($variables['element']['#parent']['#node'])) {
      $node = $variables['element']['#parent']['#node'];
      _infinite_paragraphs_get_parent_base_data($node, $variables);
    }
    elseif (isset($variables['element']['#parent']['#taxonomy_term'])) {
      $term = $variables['element']['#parent']['#taxonomy_term'];
      _infinite_paragraphs_get_parent_base_data($term, $variables);
    }
    elseif (isset($variables['element']['#parent']['#user'])) {
      $user = $variables['element']['#parent']['#user'];
      _infinite_paragraphs_get_parent_base_data($user, $variables);
    }
  }
}

/**
 * Returns first group of paragraphs suitable for the content group.
 *
 * @param array $paragraphs
 *
 * @param array $view_modes
 *
 * @return array
 */
function _infinite_paragraphs_layout_group(&$paragraphs, $view_modes) {
  $group = [];
  foreach (Element::children($paragraphs, TRUE) as $index) {
    if (in_array($paragraphs[$index]['#view_mode'], $view_modes)) {
      $group[] = $index;
    }
    elseif (!empty($group) && !in_array($paragraphs[$index]['#view_mode'], $view_modes)) {
      break;
    }
  }
  unset($paragraphs['#sorted']);
  return $group;
}

/**
 * Wraps the given group of paragraphs in a group container.
 *
 * @param array $paragraphs
 *   A list of paragraphs.
 *
 * @param array $group
 *   The indices of a group of paragraphs.
 *
 * @param $type
 *   An identifier used for the template suggestion.
 */
function _infinite_paragraphs_decorate_group(&$paragraphs, $group, $type, $build = array()) {
  if (!empty($group)) {
    $children = [];

    foreach ($group as $index) {
      $children[] = $paragraphs[$index];
      unset($paragraphs[$index]);
    }

    $paragraphs[$group[0]] = array(
      '#theme' => 'container',
      '#type' => $type,
      '#weight' => $children[0]['#weight'],
      '#children' => $children,
      '#parent' => $build,
    );

    ksort($paragraphs);

    foreach (Element::children($paragraphs) as $key => $value) {
      $paragraphs[$key] = $paragraphs[$value];
      if ($value > $key) {
        unset($paragraphs[$value]);
      }
    }

    if ($type == 'group_outer') {
      $small_group = _infinite_paragraphs_layout_group($children, array('small'));
      _infinite_paragraphs_decorate_group($paragraphs[$group[0]]['#children'], $small_group, 'group_inner', $build);
    }
  }
}

/**
 * Returns available view modes for user entities.
 *
 * @param FieldStorageDefinitionInterface $definition
 * @param FieldableEntityInterface $entity
 *
 * @return array
 */
function _infinite_paragraphs_available_user_view_modes(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
  /** @var \Drupal\Core\Entity\EntityDisplayRepositoryInterface $entityDisplayRepository */
  $entityDisplayRepository = \Drupal::service('entity_display.repository');
  // TODO maybe intersect these with allowed view modes
  $userViewModes = array_intersect_key($entityDisplayRepository->getViewModeOptions('user'), ['author_large' => '', 'author_small' => '', 'author_small_teaser' => '']);
  return $userViewModes;
}

/**
 * Returns allowed values for the paragraph view mode field.
 *
 * @param FieldStorageDefinitionInterface $definition
 * @param FieldableEntityInterface $entity
 *
 * @return array
 */
function _infinite_paragraphs_allowed_view_modes(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE) {
  $cacheable = FALSE;

  if (in_array($entity->bundle(), array('gallery', 'instagram', 'pinterest', 'recent_content', 'term_teaser', 'twitter'))) {
    $allowed_view_modes = [
      'small' => 'Schmal',
    ];
  }
  else {
    $allowed_view_modes = [
      'full' => 'Volle Breite',
      'middle' => 'Mittel',
      'small' => 'Schmal',
    ];
  }

  return $allowed_view_modes;
}

/**
 * Modifies widget for paragraph view mode.
 *
 * - Disables widget if there is only one choice.
 *
 * @param array $form_element
 */
function _infinite_paragraphs_view_mode_widget_alter(array &$element, $index) {
  if (empty($element['#default_value'])) {
    if (array_key_exists('small', $element['#options'])) {
      $element['#default_value'] = array('small');
    }
  }

  if (count(array_diff(array_keys($element['#options']), array('_none'))) == 1) {
    $element['#disabled'] = TRUE;
  }
}

function _infinite_paragraphs_get_parent_base_data(\Drupal\Core\Entity\Entity $entity, &$variables) {
  if ($entity->getEntityTypeId() == 'node') {
    $node = $entity;
    $alias_path = \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $node->id());
    if ($alias_path != '/') {
      $absolute_url = Url::fromUri('base:/' . $alias_path, array('absolute' => TRUE));
    }
    else {
      $absolute_url = Url::fromRoute('<front>', array('absolute' => TRUE));  // Extra handling for <front>.
    }
    $variables['parent']['url'] = $absolute_url->toString();
    $variables['parent']['label'] = $variables['parent']['title'];
    unset($variables['parent']['title']);
  }
  elseif ($entity->getEntityTypeId() == 'taxonomy_term') {
    $term = $entity;
    $alias_path = \Drupal::service('path.alias_manager')->getAliasByPath('/taxonomy/term/' . $term->id());
    if ($alias_path != '/') {
      $absolute_url = Url::fromUri('base:/' . $alias_path, array('absolute' => TRUE));
    }
    else {
      $absolute_url = Url::fromRoute('<front>', array('absolute' => TRUE));  // Extra handling for <front>.
    }
    $variables['parent']['url'] = $absolute_url->toString();
    $variables['parent']['label'] = $term->name->value;
  }
  elseif ($entity->getEntityTypeId() == 'user') {
    $user = $entity;
    $alias_path = \Drupal::service('path.alias_manager')->getAliasByPath('/user/' . $user->id());
    if ($alias_path != '/') {
      $absolute_url = Url::fromUri('base:/' . $alias_path, array('absolute' => TRUE));
    }
    $variables['parent']['url'] = $absolute_url->toString();
    $variables['parent']['label'] = $user->name->value;
  }

  $variables['share_img_url'] = MediaHelper::getImageUrlFromMediaReference(
    $entity,
    'field_teaser_media',
    theme_get_setting('share_image_style')
  );


  $variables['parent']['facebook_share_button'] = theme_get_setting('facebook_share_button');
  $variables['parent']['whatsapp_share_button'] = theme_get_setting('whatsapp_share_button');
  $variables['parent']['pinterest_share_button'] = theme_get_setting('pinterest_share_button');
  $variables['parent']['twitter_share_button'] = theme_get_setting('twitter_share_button');
  $variables['parent']['twitter_share_via'] = theme_get_setting('twitter_share_via');
  $variables['parent']['email_share_button'] = theme_get_setting('email_share_button');
  $variables['parent']['whatsapp_share_text'] = theme_get_setting('whatsapp_share_text');
  $variables['parent']['email_share_text'] = theme_get_setting('email_share_text');
  $variables['parent']['email_subject'] = theme_get_setting('email_subject');
}
