<?php

use Drupal\Core\Url;
use Drupal\taxonomy\Entity\Term;
use Symfony\Component\Process\Process;

/**
 * @file
 * Module for adding custom Infinity base functions.
 */

/**
 * Implements hook_ENTITY_TYPE_update() for taxonomy_term entities.
 */
function infinite_taxonomy_taxonomy_term_update(Term $term) {
  if ((\Drupal::hasService('acquia_purge.hostinginfo'))
    && $hostingInfo = \Drupal::service('acquia_purge.hostinginfo')) {

    /** @var \Drupal\acquia_purge\HostingInfo $hostingInfo */
    $site = $hostingInfo->getSiteIdentifier();
    $url = Url::fromRoute('entity.taxonomy_term.canonical', ['taxonomy_term' => $term->id()])
      ->setAbsolute(true)
      ->toString();

    $command = sprintf('curl -X PURGE -H "X-Acquia-Purge:%s" -H "Accept-Encoding: gzip" %s', $site, $url);
    $process = new Process($command);
    $process->run();
    if (!$process->isSuccessful()) {
      $errorMsg = sprintf('Unable to clear varnish cache for url %s on site %s', $url, $site);
      \Drupal::messenger()->addError($errorMsg);
    }
  }
}
