<?php

use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;

function infinite_media_theme_suggestions_image_alter(array &$suggestions, array $variables) {
  $style_name = $variables['style_name'];
  if ($style_name === NULL) {
    $style_name = 'default';
  }
  $suggestions[] = 'image__' . $style_name;
}

/**
 * Implements hook_preprocess_media().
 */
function infinite_media_preprocess_media(&$variables) {

  // todo: later possible switch to media URL for sharing media items.
  $current_url = Url::fromRoute('<current>');
  if ($node = \Drupal::routeMatch()->getParameter('node')) {  // Handling for lazy loading node URLs.
    $alias_path = \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $node->id());
    $absolute_url = Url::fromUri('base:/' . $alias_path, array('absolute' => TRUE));
  }
  else if ($current_url->toString() != '/') {
    $absolute_url = Url::fromUri('base:/' . $current_url->toString(), array('absolute' => TRUE));
  }
  else {
    $absolute_url = Url::fromRoute('<front>', array('absolute' => TRUE));  // Extra handling for <front>.
  }
  $variables['absolute_node_url'] = $absolute_url->toString();

  /* @var Media $media */
  $media = $variables['elements']['#media'];
  $variables['media_type'] = $media->bundle();
  $variables['media_id'] = $media->id();

  if ($media->bundle() === 'image') {

    // Get image dimension.
    // todo: is this really the right way?
    /* @var Image $image */
    if (!$media->field_image->isEmpty() && $media->field_image->entity) {
      $image_url = $media->field_image->entity->getFileUri();
      $image = \Drupal::service('image.factory')->get($image_url);
      if ($image->isValid()) {
        $variables['calculated_dimension'] = _infinite_media_image_dimension($image->getHeight(), $image->getWidth());

        if (theme_get_setting('share_image_style')) {
          /* @var ImageStyle $share_img */
          $share_img = ImageStyle::load(theme_get_setting('share_image_style'));
          if(is_object($share_img)) {
            $variables['share_img_url'] = $share_img->buildUrl($image_url);
          }
        }
      }
    }
  }
  else if ($media->bundle() === 'file') {
    if (!$media->field_file->isEmpty()) {
      $file_uri = $media->field_file->entity->getFileUri();
      $variables['file_url'] = file_create_url($file_uri);
    }
  }
  else if ($media->bundle() === 'video') {
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function infinite_media_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'infinite_browser') {
    $variables['view_array']['#attached']['library'][] = 'thunder_media/entity_browser_view';
  }
}

/**
 * Helper function for getting dimension of an image.
 */
function _infinite_media_image_dimension($height, $width) {
  // todo: should we handle square?
  if ($height < $width) {
    return 'landscape';
  }
  else {
    return 'portrait';
  }
}
