<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;

function infinite_ad_entity_theme_registry_alter(&$theme_registry){
  $hook = 'ad_integration_preprocess_views_view_row_fia';
  $preprocess_functions = &$theme_registry['views_view_row_fia']['preprocess functions'];
  $i = array_search($hook, $preprocess_functions);
  if($i !== FALSE){
    unset($preprocess_functions[$i]);
  }
}

/**
 * Implements hook_entity_build_defaults_alter().
 */
function infinite_ad_entity_entity_build_defaults_alter(array &$build, EntityInterface $entity, $view_mode) {
  /** @var FieldableEntityInterface $entity */
  if($entity instanceof FieldableEntityInterface
    && $entity->hasField('field_header_blocks')
    && !$entity->get('field_header_blocks')->isEmpty()){

    /** @var \Drupal\Core\Theme\ActiveTheme $theme */
    $theme = \Drupal::service('theme.manager')->getActiveTheme();
    $base_themes = $theme->getBaseThemes();

    if(array_key_exists('infinite_amp', $base_themes)) {
      // Replace defined ad blocks by the corresponding amp ad blocks.
      $header_blocks = $entity->get('field_header_blocks')->getValue();
      foreach ($header_blocks as $key => &$header_block) {
        $block = \Drupal::entityTypeManager()
          ->getStorage('block')
          ->load($header_block['target_id']);

        if(isset($block) && $block->getPlugin() == 'ad_entity_block') {

          $replacement_block_id = $header_block['target_id'] . '_amp';
          $replacement_block = \Drupal::entityTypeManager()
            ->getStorage('block')
            ->load($replacement_block_id);

          if(isset($replacement_block)){
            $header_block['target_id'] = $replacement_block_id;
          }
          else {
            unset($header_blocks[$key]);
          }

        }
      }
      $entity->set('field_header_blocks', $header_blocks);
    }

  }

}

function infinite_ad_entity_preprocess_views_view_row_fia(&$variables) {
  /** @var \Drupal\ad_entity\Plugin\AdContextManager $context_manager */
  if ($context_manager = \Drupal::service('ad_entity.context_manager')) {
    /** @var \Drupal\views\ResultRow $row */
    $row = $variables['options']['row'];
    $entity = $row->_entity;
    $context_manager->resetContextDataForEntity($entity);

    $ad_entity = \Drupal::entityTypeManager()
      ->getStorage('ad_entity')
      ->load('adtech_facebook_instant_article');
    $view_builder = \Drupal::entityTypeManager()
      ->getViewBuilder($ad_entity->getEntityTypeId());
    $variables['options']['automatic_ad'] = $view_builder->view($ad_entity);

    // Reset to previous context data state (if any).
    $variables['options']['automatic_ad']['#post_render'][] = '_ad_entity_reset_to_previous_context_data';
  }
}

function infinite_ad_entity_theme_suggestions_ad_entity_alter(array &$suggestions, array $variables, $hook){
  $suggestions[] = $hook . '__' . $variables['ad_entity']->id();
}

function infinite_ad_entity_preprocess_dfp_amp(&$vars){

  if(isset($vars['json']['targeting']['channel'])) {
    $targeting = $vars['json']['targeting'];
    $channel = is_array($targeting['channel']) ? reset($targeting['channel']) : $targeting['channel'];
    $channel = str_replace('homepage/', '', $channel);
    unset($targeting['channel']);
    $vars['json']['targeting'] = $targeting;

    /** @var Drupal\Core\Template\Attribute $attributes */
    $attributes = &$vars['attributes'];
    $attributes['data-slot'] = str_replace('/amp', '/' . $channel, $attributes['data-slot']);
  }

}
