<?php

use Drupal\Component\Serialization\Json;

function infinite_ad_entity_theme_registry_alter(&$theme_registry){
  $hook = 'ad_integration_preprocess_views_view_row_fia';
  $preprocess_functions = &$theme_registry['views_view_row_fia']['preprocess functions'];
  $i = array_search($hook, $preprocess_functions);
  if($i !== FALSE){
    unset($preprocess_functions[$i]);
  }
}

function infinite_ad_entity_preprocess_views_view_row_fia(&$variables) {
  /** @var \Drupal\ad_entity\Plugin\AdContextManager $context_manager */
  if ($context_manager = \Drupal::service('ad_entity.context_manager')) {
    /** @var \Drupal\views\ResultRow $row */
    $row = $variables['options']['row'];
    $entity = $row->_entity;
    $context_manager->resetContextDataForEntity($entity);

    $ad_entity = \Drupal::entityTypeManager()
      ->getStorage('ad_entity')
      ->load('adtech_facebook_instant_article');
    $view_builder = \Drupal::entityTypeManager()
      ->getViewBuilder($ad_entity->getEntityTypeId());
    $variables['options']['automatic_ad'] = $view_builder->view($ad_entity);

    // Reset to previous context data state (if any).
    $variables['options']['automatic_ad']['#post_render'][] = '_ad_entity_reset_to_previous_context_data';
  }
}

function infinite_ad_entity_theme_suggestions_ad_entity_alter(array &$suggestions, array $variables, $hook){
  $suggestions[] = $hook . '__' . $variables['ad_entity']->id();
}

function infinite_ad_entity_preprocess_dfp_amp(&$vars){
  $targeting = Json::decode($vars['targeting']);
  $channel = str_replace('homepage/', '', $targeting['channel']);
  unset($targeting['channel']);
  $vars['targeting'] = Json::encode($targeting);

  /** @var Drupal\Core\Template\Attribute $attributes */
  $attributes = &$vars['attributes'];
  $attributes['data-slot'] = str_replace('/amp', '/' . $channel, $attributes['data-slot']);
}
