<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_build_defaults_alter().
 */
function infinite_article_node_build_defaults_alter(array &$build, EntityInterface $node, $view_mode) {

  if($node->bundle() == 'article' && !$node->get('field_header_blocks')->isEmpty()){

    if ($view_mode == 'lazyloading') {
      // Replace 'advertisingslot_banner_any' with 'advertisingslot_banner_any_2' in header blocks on lazyloading.
      $header_blocks = $node->get('field_header_blocks')->getValue();
      foreach ($header_blocks as $key => &$header_block) {
        if ($header_block['target_id'] == 'advertisingslot_banner_any') {
          $header_block['target_id'] = 'advertisingslot_banner_any_2';
          $node->set('field_header_blocks', $header_blocks);
        }
        else {
          if (\Drupal::moduleHandler()
              ->moduleExists('ad_entity') && $header_block['target_id'] == 'adblock_full_article'
          ) {
            $header_block['target_id'] = 'adblock_full_article_2';
            $node->set('field_header_blocks', $header_blocks);
          }
        }
      }
    }
  }

}
