<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_build_defaults_alter().
 */
function infinite_article_node_build_defaults_alter(array &$build, EntityInterface $node, $view_mode) {
  if ($view_mode == 'lazyloading' &&
      $node->bundle() == 'article' &&
      !$node->get('field_header_blocks')->isEmpty()) {

    // Replace 'advertisingslot_banner_any' with 'advertisingslot_banner_any_2' in header blocks on lazyloading.
    $header_blocks = $node->get('field_header_blocks')->getValue();
    foreach ($header_blocks as $key => &$header_block) {
      if ($header_block['target_id'] == 'advertisingslot_banner_any') {
        $header_block['target_id'] = 'advertisingslot_banner_any_2';
        $node->set('field_header_blocks', $header_blocks);
      }
    }
  }
}

/**
 * Implements hook_form_node_article_edit_form_alter().
 */
function infinite_article_form_node_article_edit_form_alter(&$form, FormStateInterface $form_state) {
  _infinite_article_form_alter_helper($form, $form_state);
}

/**
 * Implements hook_form_node_article_form_alter().
 */
function infinite_article_form_node_article_form_alter(&$form, FormStateInterface $form_state) {
  _infinite_article_form_alter_helper($form, $form_state);
}

/**
 * Helper function for article form alter hooks.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function _infinite_article_form_alter_helper(&$form, FormStateInterface $form_state) {
  // Move field_promote_states to options group.
  $form['field_promote_states']['#group'] = 'options';
  $form['field_hide_created']['#group'] = 'author';
}
